services:
  naive:
    image: andynechen/naiveproxy:20220825
    restart: always
    volumes:
      - ./Caddy/Caddyfile:/etc/naiveproxy/Caddyfile
      - ./var/www/html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
