services:
  naive:
    image: andynechen/naiveproxy:20220825
    restart: always
    volumes:
      - ./config:/etc/naiveproxy
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
